openapi: 3.0.0
info:
  title: Home task 3
  description: Radency internship
  version: 0.0.1

servers:
  - url: http://localhost:4000
    description: Dev server
tags:
  - name: Notes
paths:
  /notes:
    $ref: './methods/notes.yml'
  /notes/{id}:
    $ref: './methods/noteById.yml'
  /notes/stats:
    $ref: './methods/stats.yml'
